apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: core-components
  namespace: flux-system
spec:
  recurseSubmodules: true
  interval: 0m30s
  url: "https://github.com/n-barnes/flux-cluster-b"
  ref:
    branch: master

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-components
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: core-components
  path: "./cluster-config/core-applications"
  prune: true
  timeout: 1m
