apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: core-components
  namespace: flux-system
spec:
  recurseSubmodules: true
  interval: 0m30s
  url: https://github.com/n-barnes/core-applications.git
  ref:
    tag: 1.0.1

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-components
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: core-components
  prune: true
  timeout: 1m
